### ISSUE TITLE
Part1 + Part2: No error message when invalid car is queried

### ISSUE THREAD

**Issue by Henchway** [SDE-Service-Engineering-Project/se_frontend#49]
Steps to reproduce:
1. go to rent a car
2. change the id to something that doesn't exist
3. expect an error message
Reality: No error message, although the response body has the 'message' key specified.

![image](https://user-images.githubusercontent.com/37119321/236623797-9832d129-6365-4d31-8a46-35d0a683aa88.png)

**Comment by mashkie** [comment]
fixed with https://github.com/SDE-Service-Engineering-Project/se_frontend/pull/50 https://github.com/SDE-Service-Engineering-Project/se_frontend/pull/51 for part 1 and 2
